/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.CFuncoes;
import Control.CPintura;
import Control.Controle;
import Model.Classificacao.Prismas;
import Model.Poligono;
import Model.Vertice;
import Model.manipulation.CFuncoes;
import Model.manipulation.CPintura;
import Model.manipulation.Controle;
import Model.transformacao.Escala;
import Model.transformacao.Rotacao;
import Model.visualizacao.Camera;
import Model.visualizacao.Cena;
import java.awt.Point;
import javafx.scene.Camera;
import javafx.scene.control.Control;

/**
 *
 * @author Maycon
 */
public class MainV extends javax.swing.JFrame {

    Cena cena = Controle.getCena();
    
    Poligono poligonoSelecinado;
    Vertice vi;
    Vertice vf;
    Point origemLateral, origemTopo, origemPerspectiva, origemFrontal;

    /**
     * Creates new form Principal
     */
    public MainV() {
        initComponents();
        CPintura.setG1(vFrente.getGraphics());
        Camera.getCamera().init();

        origemFrontal = vFrente.getLocation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        vFrente = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbMover = new javax.swing.JToggleButton();
        jbRedimensionar = new javax.swing.JToggleButton();
        jbRotacionar = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfLadosPrisma = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vFrente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Frente"));
        vFrente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                vFrenteMouseDragged(evt);
            }
        });
        vFrente.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                vFrenteMouseWheelMoved(evt);
            }
        });
        vFrente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vFrenteMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vFrenteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout vFrenteLayout = new javax.swing.GroupLayout(vFrente);
        vFrente.setLayout(vFrenteLayout);
        vFrenteLayout.setHorizontalGroup(
            vFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
        );
        vFrenteLayout.setVerticalGroup(
            vFrenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ferramentas"));
        jPanel2.setToolTipText("");

        buttonGroup1.add(jbMover);
        jbMover.setText("Mover");

        buttonGroup1.add(jbRedimensionar);
        jbRedimensionar.setText("Redimensionar");

        buttonGroup1.add(jbRotacionar);
        jbRotacionar.setText("Rotacionar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbRedimensionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(jbRotacionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbMover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbMover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbRedimensionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbRotacionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Objetos"));

        jLabel2.setText("Quantidade de lados");

        jButton1.setText("Gerar prisma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfLadosPrisma)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfLadosPrisma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vFrente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vFrente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int A = Integer.parseInt(jtfLadosPrisma.getText());

        Controle.addSolido( Prismas.porCodigo(A));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vFrenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vFrenteMouseClicked
        if (poligonoSelecinado != null) { // caso haja um poligono selecionado então tira o seu destaque.
            CPintura.PintarBordasPoligono(poligonoSelecinado);
        }
        // pegando ponto do clique 
        Vertice v = new Vertice();
        v.setX(evt.getPoint().x);
        v.setY(evt.getPoint().y);
        // pega o poligono q foi selecionado
        poligonoSelecinado = CFuncoes.getPoligonoSelecionadoVistaFrontal(v);
        // Destaca o poligono que foi selecionado
        if (poligonoSelecinado != null) {
            CPintura.PintarBordasPoligono(poligonoSelecinado);
        }
    }//GEN-LAST:event_vFrenteMouseClicked

    private void vFrenteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vFrenteMouseReleased
        vi = null;
    }//GEN-LAST:event_vFrenteMouseReleased

    private void vFrenteMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vFrenteMouseDragged
        // Aperta e Arrasta
        if (jbMover.isSelected() && poligonoSelecinado != null) {
            if (vi == null) {
                vi = new Vertice();
                vi.setX(evt.getPoint().x);
                vi.setY(evt.getPoint().y);
                vi.setZ(0);
            } else {
                vf = new Vertice();
                vf.setX(evt.getPoint().x);
                vf.setY(evt.getPoint().y);
                vf.setZ(0);

                CFuncoes.mover(poligonoSelecinado, vi, vf);
                poligonoSelecinado.setAllScanlines(false);
                
                //Controle.PintarBordasPoligos();
                //CPintura.PintarCena();
                Controle.paintPolygons();

                vi = vf;
            }
        }
        if (jbRotacionar.isSelected() && poligonoSelecinado != null) {
            if (vi == null) {
                vi = new Vertice();
                vi.setX(evt.getPoint().x);
            } else {
                vf = new Vertice();
                vf.setX(evt.getPoint().x);
                
                Rotacao r = new Rotacao(0.5, Rotacao.Orientacao.ROTACAOX);
                if (vi.getX() < vf.getX()) {
                    CFuncoes.rotaciona(poligonoSelecinado, r.getMatrizRotacao());
                } else {
                    CFuncoes.rotaciona(poligonoSelecinado, r.getMatrizRotacao());
                }
                
                poligonoSelecinado.setAllScanlines(false);
                Controle.paintPolygons();
                vi = vf;
            }
        }
    }//GEN-LAST:event_vFrenteMouseDragged

    private void vFrenteMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_vFrenteMouseWheelMoved
        // Scroll do mouse
        if (poligonoSelecinado != null) {
            int voltas = evt.getWheelRotation();
            //System.out.println("num voltas: "+ voltas);
            float escalar = 1;
            escalar += voltas * 0.1;

            Escala e = new Escala(escalar, Escala.Tipo.EscalaXYZ);
            CFuncoes.escala(poligonoSelecinado, e.getMatrizEscala()); //MATRIZ DE TRANSFORMACAO; TROCAR
            Controle.paintPolygons();
        }
    }//GEN-LAST:event_vFrenteMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jbMover;
    private javax.swing.JToggleButton jbRedimensionar;
    private javax.swing.JToggleButton jbRotacionar;
    private javax.swing.JTextField jtfLadosPrisma;
    private javax.swing.JPanel vFrente;
    // End of variables declaration//GEN-END:variables
}
